version: '3.9'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"

  mongoexpress:
    image: mongo-express
    ports:
      - "8081:8081"
    environment: 
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
    depends_on:
      - mongo
    restart: always

volumes:
  mongo_data:
    driver: local
 
networks:
  default:
    external:
      name: mongo-school-network